### ISSUE TITLE
Step 1: Build Trust

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#15]
1) Design Implementation
2) Social Networks connection

**Comment by EmileKrm** [comment]
*** User Story ***

As a **User** I want to connect **my social media** so that **my application gets higher chances of being accepted**

*** Acceptance criteria ***
- [ ] User must be able to connect Facebook
- [ ] User must be able to connect Linkedin
- [ ] User must be able to connect Google
- [ ] User must be able to connect Paypal
- [ ] User must be able to connect twitter
- [ ] User must be able to see his trust level increase when additional accounts are connected

*** Definition of done ***

Verify correct storage of social media information by connecting different accounts of test user

**Comment by yuliyasychugova** [comment]
Thanks for such a rich descrioption and acceptance criteria! Appreciate it.

**Comment by EmileKrm** [comment]
No problem, the important thing is to simplify communications as much as possible :)
Do you think we should keep this task to a simple issue or convert it to an epic (Group of issues) ?
I have a feeling that it is a lot of work: Progress bar logic + trust bar logic + social connects + Front end design

**Comment by yuliyasychugova** [comment]
@EmileKrm  I think checkbox is enough though it's up to you at last :)

**Comment by EmileKrm** [comment]
Alright let's keep it this way then
