### ISSUE TITLE
Public Pages

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#89]
Since we're doing every template responsible and according to pixel-perfect approach, it takes time to make every page looks as you want it to look.
So, in details, block by block, it's like:

- [ ] Blocks 'Build a certified..' (2 hours)
- [ ] 'Need a French...' (2 hours)
- [ ] 'Increase your chances...' (2 hours)
- [ ] Block 'How does it work?'  (5 hours), including inner similar blocks.
- [ ] Block 'We already work...' will take about (1.5 hours).
- [ ] Testimonial (2.5 hours) --> Let's drop this part
- [ ] Contact us card (1 .5 hours)
